---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
before_script: bundle exec rake spec_prep
script: bundle exec rake spec
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.18
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.18
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.6.18
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.23
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.0.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.1.1
    - rvm: 2.1.2
      env: PUPPET_VERSION=2.6.18
    - rvm: 2.1.2
      env: PUPPET_VERSION=2.7.23
    - rvm: 2.1.2
      env: PUPPET_VERSION=3.0.2
    - rvm: 2.1.2
      env: PUPPET_VERSION=3.1.1
    - rvm: 2.1.2
      env: PUPPET_VERSION=3.2.4
    - rvm: 2.1.2
      env: PUPPET_VERSION=3.3.2
    - rvm: 2.1.2
      env: PUPPET_VERSION=3.4.3