name         'gsteven-rsyslog'
version      '1.0.0'
author       'Gary Steven'
license      'Apache 2.0'
summary      'Puppet Module to Manage rsyslog'
description  'Puppet Module to Manage rsyslog'
project_page ''
source       ''
dependency   'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
